---
 - hosts: all
   become: true
   gather_facts: true

   tasks:
   - name: install packages
     yum:
       name:
       - bind
       - bind-utils
       - ntp
       - nano
       state: present

   - name: copy transferkey to all servers and the client
     copy:
       src: ../provisioning/named.zonetransfer.key
       dest: /etc/named.zonetransfer.key
       owner: root
       group: named
       mode: 0644

 - hosts: ns01
   become: true
   tasks:
   - name: copy named.conf
     copy:
       src: ../provisioning/master-named.conf
       dest: /etc/named.conf
       owner: root
       group: named
       mode: 0640
   - name: copy zones
     copy:
       src: "{{ item }}"
       dest: /etc/named/
       owner: root
       group: named
       mode: 0660
     with_fileglob:
       - ../provisioning/named.d*
       - ../provisioning/named.n*

   - name: copy resolv.conf to the servers
     copy:
       src: ../provisioning/servers-resolv.conf
       dest: /etc/resolv.conf
       owner: root
       group: root
       mode: 0644

   - name: set /etc/named permissions
     file:
       path: /etc/named
       owner: root
       group: named
       mode: 0670

   - name: ensure named is running and enabled
     service:
       name: named
       state: restarted
       enabled: yes

 - hosts: ns02
   become: true
   tasks:
   - name: copy named.conf
     copy:
       src: ../provisioning/slave-named.conf
       dest: /etc/named.conf
       owner: root
       group: named
       mode: 0640

   - name: copy resolv.conf to the servers
     copy:
       src: ../provisioning/servers-resolv.conf
       dest: /etc/resolv.conf
       owner: root
       group: root
       mode: 0644

   - name: set /etc/named permissions
     file:
       path: /etc/named
       owner: root
       group: named
       mode: 0670
  
   - name: ensure named is running and enabled
     service:
       name: named
       state: restarted
       enabled: yes
  
   - name: install policycoreutils-python
     yum:
       name: policycoreutils-python
       state: present

   - name: Change the named_t domain to permissive
     selinux_permissive:
       name: named_t
       permissive: true

   - name: restart named
     service:
       name: named
       state: restarted

 - hosts: client
   become: true
   tasks:
   - name: copy resolv.conf to the client
     copy:
       src: ../provisioning/client-resolv.conf
       dest: /etc/resolv.conf
       owner: root
       group: root
       mode: 0644

   - name: copy rndc conf file
     copy:
       src: ../provisioning/rndc.conf
       dest: /home/vagrant/rndc.conf
       owner: vagrant
       group: vagrant
       mode: 0644

   - name: copy motd to the client
     copy:
       src: ../provisioning/client-motd
       dest: /etc/motd
       owner: root
       group: root
       mode: 0644

 - hosts: client2
   become: true
   tasks:
   - name: copy resolv.conf to the client
     copy:
       src: ../provisioning/client-resolv.conf
       dest: /etc/resolv.conf
       owner: root
       group: root
       mode: 0644

   - name: copy rndc conf file
     copy:
       src: ../provisioning/rndc.conf
       dest: /home/vagrant/rndc.conf
       owner: vagrant
       group: vagrant
       mode: 0644

   - name: copy motd to the client
     copy:
       src: ../provisioning/client-motd
       dest: /etc/motd
       owner: root
       group: root
       mode: 0644
